name: Sync Upstream  # 工作流名称

on:
  schedule:
    - cron: '0 * * * *'  # 每小时运行一次的定时器
  workflow_dispatch:  # 通过手动触发运行工作流

jobs:
  sync:
    runs-on: ubuntu-latest  # 在最新版的 Ubuntu 环境中运行

    steps:
    - name: Checkout code  # 步骤名称：检出代码
      uses: actions/checkout@v2  # 使用 GitHub 提供的 actions/checkout 操作
      with:
        fetch-depth: 0  # 获取所有历史提交

    - name: Sync upstream  # 步骤名称：同步上游
      run: |
        git config --global user.name 'GitHub Actions'  # 设置 Git 用户名
        git config --global user.email 'actions@github.com'  # 设置 Git 用户邮箱
        git remote add upstream https://github.com/cmliu/edgetunnel.git  # 添加上游仓库
        git fetch upstream  # 获取上游仓库最新更改
        git checkout main  # 切换到本地主分支
        git merge upstream/main  # 合并上游仓库的主分支到本地主分支
        git push origin main  # 将本地主分支推送到远程仓库
